services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8501:8501"
    environment:
      - API_ENDPOINT=http://backend:5000
    networks:
      - summarizer-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "5000:5000"
    networks:
      - summarizer-network
    env_file:
      - back/.env

networks:
  summarizer-network:
